name: movie_rec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - scipy
      - matplotlib
      - seaborn
      - scikit-surprise
      - tensorflow
      - shap
      - lime
      - pytest
      - flake8
      - black